### Get all ice vehicle years
GET http://localhost:8080/api/ice/years
Accept: application/json

### Get all makes of said year
GET http://localhost:8080/api/ice/years/2012
Accept: application/json

### Get all models of said make
GET http://localhost:8080/api/ice/years/2012/ford
Accept: application/json


### Get all states
GET http://localhost:8080/api/ice/states
Accept: application/json

//http//localhost:8080/api/ice/userVehicle/ + userStateId

### Get the user's state info on the comparison page (Alaska)
GET http://localhost:8080/api/ice/userVehicle/133
Accept: application/json

//http://localhost:8080/api/ice/userVehicle/" + userYearId + "/" + userMakeId + "/" + userModelId
### Get the user's vehicle from the submit button (2012 Ford F-150)
GET http://localhost:8080/api/ice/userVehicle/151/153/155
Accept: application/json